stack_dir: /home/ubuntu/stacks
vpn_region: "Netherlands"
wireguard_addresses: "100.108.214.254/32"
stack_env:
  WIREGUARD_PRIVATE_KEY: "{{ vault_wg_private_key }}"
  WIREGUARD_PRESHARED_KEY: "{{ vault_wg_preshared_key }}"
  WIREGUARD_ADDRESSES: "{{ wireguard_addresses }}"
  VPN_REGION: "{{ vpn_region }}"
